requires "Kossy", 0.38;
requires "DBIx::Sunny";

requires "DBD::mysql";
requires "Starman";
requires "Plack::Session";
requires "Gazelle";
requires "Cache::Memcached::Fast";
requires "Sereal";
requires "Digest::SHA";
